import { type BrandDefinition, type Build, type DemoOrder, type Product, type ProductReview, type VehicleGeneration, type VehicleRecord } from "@/lib/types";

const range = (start: number, end: number) =>
  Array.from({ length: end - start + 1 }, (_, index) => start + index);

export const brands: BrandDefinition[] = [
  {
    slug: "bmw",
    name: "BMW",
    tagline: "Motorsport-born aero and chassis styling.",
    heroImage: "/assets/brand-bmw.svg",
    description: "Carbon-led styling and fitment-focused upgrades for modern BMW chassis.",
    featuredGenerationSlug: "g20",
    megaMenu: [
      { label: "3 Series", items: ["F30 / F31", "G20 / G21", "G80 M3"] },
      { label: "4 Series", items: ["F32 / F33 / F36", "G22 / G23 / G26", "G82 / G83 M4"] },
      { label: "5 Series", items: ["F10", "G30", "G60"] },
      { label: "M Cars", items: ["F80 M3", "F82 M4", "F90 M5", "G80 M3", "G82 M4"] },
    ],
  },
  {
    slug: "mercedes-benz",
    name: "Mercedes-Benz",
    tagline: "Sharper silhouette. Executive aggression.",
    heroImage: "/assets/brand-mercedes-benz.svg",
    description: "OEM-plus and black-series inspired styling for AMG and sport package platforms.",
    featuredGenerationSlug: "w206",
    megaMenu: [
      { label: "C-Class", items: ["W205", "W206", "C63 AMG"] },
      { label: "E-Class", items: ["W213", "W214", "E53 AMG"] },
      { label: "CLA / A-Class", items: ["W118 CLA", "W177 A-Class", "AMG 45"] },
      { label: "SUV", items: ["X253 GLC", "C254 GLC Coupe", "GLE Coupe"] },
    ],
  },
  {
    slug: "audi",
    name: "Audi",
    tagline: "RS-inspired aero with precise platform coverage.",
    heroImage: "/assets/brand-audi.svg",
    description: "Visual and dynamic upgrades for S and RS-minded Audi owners.",
    featuredGenerationSlug: "b9",
    megaMenu: [
      { label: "A3 / S3 / RS3", items: ["8V", "8Y", "RS3 Sedan"] },
      { label: "A4 / S4 / RS4", items: ["B8.5", "B9", "B10"] },
      { label: "A5 / S5 / RS5", items: ["B8.5", "B9 Sportback", "B10"] },
      { label: "SUV", items: ["Q5", "SQ5", "RSQ8"] },
    ],
  },
  {
    slug: "porsche",
    name: "Porsche",
    tagline: "Track-bred restraint with premium composite details.",
    heroImage: "/assets/brand-porsche.svg",
    description: "Purposeful exterior and interior enhancements for sports-car focused builds.",
    featuredGenerationSlug: "982",
    megaMenu: [
      { label: "718", items: ["982 Cayman", "982 Boxster", "GT4 / Spyder"] },
      { label: "911", items: ["991.2", "992.1", "992 GT3"] },
      { label: "Panamera", items: ["971", "972"] },
      { label: "SUV", items: ["Macan", "Cayenne Coupe", "Taycan Cross Turismo"] },
    ],
  },
];

export const vehicleGenerations: VehicleGeneration[] = [
  {
    slug: "g20",
    makeSlug: "bmw",
    modelSlug: "3-series",
    modelName: "3 Series",
    name: "G20 / G21",
    chassisLabel: "G20",
    years: range(2019, 2026),
    trims: ["330i", "330e", "M340i"],
    notes: "Sedan and touring chassis. LCI fitment restrictions vary by product.",
  },
  {
    slug: "g80-m3",
    makeSlug: "bmw",
    modelSlug: "m3",
    modelName: "M3",
    name: "G80 M3",
    chassisLabel: "G80",
    years: range(2021, 2026),
    trims: ["M3", "M3 Competition", "M3 CS"],
  },
  {
    slug: "g82-m4",
    makeSlug: "bmw",
    modelSlug: "m4",
    modelName: "M4",
    name: "G82 / G83 M4",
    chassisLabel: "G82",
    years: range(2021, 2026),
    trims: ["M4", "M4 Competition", "M4 CSL"],
  },
  {
    slug: "f80-m3",
    makeSlug: "bmw",
    modelSlug: "m3",
    modelName: "M3",
    name: "F80 M3",
    chassisLabel: "F80",
    years: range(2015, 2018),
    trims: ["M3", "M3 Competition", "M3 CS"],
  },
  {
    slug: "w206",
    makeSlug: "mercedes-benz",
    modelSlug: "c-class",
    modelName: "C-Class",
    name: "W206",
    chassisLabel: "W206",
    years: range(2022, 2026),
    trims: ["C300", "C43 AMG", "C63 S E Performance"],
  },
  {
    slug: "w118-cla",
    makeSlug: "mercedes-benz",
    modelSlug: "cla-class",
    modelName: "CLA",
    name: "W118 / C118",
    chassisLabel: "W118",
    years: range(2020, 2026),
    trims: ["CLA45 AMG"],
  },
  {
    slug: "b85",
    makeSlug: "audi",
    modelSlug: "a4",
    modelName: "A4 / S4 / A5 / S5",
    name: "B8.5",
    chassisLabel: "B8.5",
    years: range(2013, 2016),
    trims: ["A4", "S4", "A5", "S5"],
  },
  {
    slug: "b9",
    makeSlug: "audi",
    modelSlug: "a4",
    modelName: "A4 / S4 / RS4",
    name: "B9",
    chassisLabel: "B9",
    years: range(2017, 2025),
    trims: ["A4", "S4", "RS4"],
  },
  {
    slug: "8y-rs3",
    makeSlug: "audi",
    modelSlug: "rs3",
    modelName: "RS3",
    name: "8Y RS3",
    chassisLabel: "8Y",
    years: range(2022, 2026),
    trims: ["RS3 Sedan", "RS3 Sportback"],
  },
  {
    slug: "982",
    makeSlug: "porsche",
    modelSlug: "718",
    modelName: "718 Cayman / Boxster",
    name: "982",
    chassisLabel: "982",
    years: range(2017, 2025),
    trims: ["Cayman", "Cayman S", "GTS 4.0", "GT4"],
  },
  {
    slug: "992",
    makeSlug: "porsche",
    modelSlug: "911",
    modelName: "911",
    name: "992.1",
    chassisLabel: "992",
    years: range(2020, 2026),
    trims: ["Carrera", "Carrera S", "Turbo", "GT3"],
  },

  {
    slug: "9y-cayenne",
    makeSlug: "porsche",
    modelSlug: "cayenne",
    modelName: "Cayenne",
    name: "9YA / 9YB",
    chassisLabel: "9Y",
    years: range(2019, 2026),
    trims: ["Cayenne", "Cayenne S", "Cayenne Coupe", "Cayenne GT"],
  },
  {
    slug: "95b-macan",
    makeSlug: "porsche",
    modelSlug: "macan",
    modelName: "Macan",
    name: "95B",
    chassisLabel: "95B",
    years: range(2015, 2021),
    trims: ["Macan", "Macan S", "Macan GTS", "Macan Turbo"],
  },
];

export const vehicleRecords: VehicleRecord[] = vehicleGenerations.flatMap((generation) =>
  generation.years.flatMap((year) =>
    generation.trims.map((trim) => ({
      key: `${year}-${generation.makeSlug}-${generation.modelSlug}-${generation.slug}-${trim.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
      year,
      makeSlug: generation.makeSlug,
      makeName: brands.find((brand) => brand.slug === generation.makeSlug)?.name || generation.makeSlug,
      modelSlug: generation.modelSlug,
      modelName: generation.modelName,
      generationSlug: generation.slug,
      generationName: generation.name,
      chassisLabel: generation.chassisLabel,
      trim,
      label: `${year} ${brands.find((brand) => brand.slug === generation.makeSlug)?.name || generation.makeSlug} ${trim} ${generation.chassisLabel}`,
    }))
  )
);

const baseFaq = [
  {
    question: "Does AeroHaus verify fitment before shipping?",
    answer: "Yes. If your selected vehicle or order notes suggest a possible mismatch, our team reviews the order before it is released.",
  },
  {
    question: "Are installation instructions included?",
    answer: "Products include hardware and notes when supplied by the manufacturer. Professional installation is recommended for composite and painted aero components.",
  },
];

export const products: Product[] = [
  {
    id: "prod_g20_front_lip",
    slug: "g20-m-performance-carbon-front-lip",
    brandSlug: "bmw",
    brandName: "BMW",
    categorySlug: "front-lips",
    categoryName: "Front Lips",
    title: "BMW G20 M Performance Style Carbon Fiber Front Lip",
    shortDescription: "Pre-preg carbon front lip for G20/G21 M Sport and M340i front bumpers.",
    description: "A three-piece, motorsport-inspired lower aero upgrade developed around the G20/G21 M Sport profile. The demo catalog content is structured to be swapped with production descriptions once supplier-approved assets are ready.",
    price: 449,
    compareAtPrice: 549,
    status: "Active",
    badges: ["BEST SELLER", "SALE"],
    rating: 4.9,
    reviewCount: 42,
    featured: true,
    bestSeller: true,
    newArrival: false,
    materialOptions: ["Pre-preg Carbon Fiber", "FRP"],
    finishOptions: ["Gloss", "Matte", "Unpainted"],
    gallery: ["/assets/products/g20-m-performance-carbon-front-lip-1.svg", "/assets/products/g20-m-performance-carbon-front-lip-2.svg", "/assets/products/g20-m-performance-carbon-front-lip-3.svg"],
    compatibilitySummary: "2019-2026 BMW 3 Series G20/G21 | M Sport / M340i",
    fitments: [{ generationSlug: "g20", yearStart: 2019, yearEnd: 2026, trims: ["330i", "M340i"], exact: true, notes: "Fits G20/G21 models equipped with the M Sport front bumper. Verify fitment before ordering.", exclusions: ["Does not fit base bumper"], requires: ["M Sport bumper"] }],
    variants: [
      { id: "var_g20_front_lip_gloss", sku: "AH-G20-FLIP-CF-GLS", material: "Pre-preg Carbon Fiber", finish: "Gloss", optionLabel: "Gloss Carbon Fiber", price: 449, compareAtPrice: 549, inventory: 9 },
      { id: "var_g20_front_lip_matte", sku: "AH-G20-FLIP-CF-MAT", material: "Pre-preg Carbon Fiber", finish: "Matte", optionLabel: "Matte Carbon Fiber", price: 459, compareAtPrice: 559, inventory: 4 },
      { id: "var_g20_front_lip_frp", sku: "AH-G20-FLIP-FRP-UNP", material: "FRP", finish: "Unpainted", optionLabel: "FRP / Unpainted", price: 319, inventory: 7 },
    ],
    shippingWindow: { processingBusinessDays: "2-5 Business Days", deliveryBusinessDays: "7-18 Business Days" },
    installation: "Professional installation recommended. Test fit before final fastening on composite parts.",
    whatsIncluded: ["Front lip set", "Mounting hardware", "Protective edge tape"],
    faq: baseFaq,
    relatedSlugs: ["g20-m340i-carbon-mirror-caps", "g20-m-style-rear-diffuser", "bmw-g20-coilover-kit"],
  },
  {
    id: "prod_g80_grille",
    slug: "g80-csl-style-carbon-grille",
    brandSlug: "bmw",
    brandName: "BMW",
    categorySlug: "grilles",
    categoryName: "Grilles",
    title: "BMW G80 CSL Style Carbon Grille",
    shortDescription: "Open-weave CSL-inspired grille surround for G80 M3 front fascia.",
    description: "Designed to sharpen the front profile of the G80 with a darker, more technical weave and premium gloss clear.",
    price: 389,
    compareAtPrice: 469,
    status: "Active",
    badges: ["NEW"],
    rating: 4.8,
    reviewCount: 18,
    featured: true,
    bestSeller: false,
    newArrival: true,
    materialOptions: ["Carbon Fiber"],
    finishOptions: ["Gloss"],
    gallery: ["/assets/products/g80-csl-style-carbon-grille-1.svg", "/assets/products/g80-csl-style-carbon-grille-2.svg", "/assets/products/g80-csl-style-carbon-grille-3.svg"],
    compatibilitySummary: "2021-2026 BMW G80 M3",
    fitments: [{ generationSlug: "g80-m3", yearStart: 2021, yearEnd: 2026, trims: ["M3", "M3 Competition", "M3 CS"], exact: true, notes: "Fits G80 M3 sedan including Competition models." }],
    variants: [{ id: "var_g80_grille_gloss", sku: "AH-G80-GRL-CF-GLS", material: "Carbon Fiber", finish: "Gloss", optionLabel: "Gloss Carbon", price: 389, compareAtPrice: 469, inventory: 11 }],
    shippingWindow: { processingBusinessDays: "2-4 Business Days", deliveryBusinessDays: "7-14 Business Days" },
    installation: "Direct replacement. Professional trim removal tools recommended.",
    whatsIncluded: ["Left grille insert", "Right grille insert"],
    faq: baseFaq,
    relatedSlugs: ["g82-carbon-side-skirts", "g20-m-performance-carbon-front-lip"],
  },
  {
    id: "prod_g82_skirts",
    slug: "g82-carbon-side-skirts",
    brandSlug: "bmw",
    brandName: "BMW",
    categorySlug: "side-skirts",
    categoryName: "Side Skirts",
    title: "BMW G82 Carbon Side Skirts",
    shortDescription: "Extended rocker profile for G82/G83 M4 with gloss composite finish.",
    description: "Adds visual length and lower side definition while following the G82 sill contour.",
    price: 699,
    status: "Preorder",
    badges: ["PREORDER"],
    rating: 4.7,
    reviewCount: 9,
    featured: false,
    bestSeller: false,
    newArrival: true,
    materialOptions: ["Carbon Fiber"],
    finishOptions: ["Gloss"],
    gallery: ["/assets/products/g82-carbon-side-skirts-1.svg", "/assets/products/g82-carbon-side-skirts-2.svg", "/assets/products/g82-carbon-side-skirts-3.svg"],
    compatibilitySummary: "2021-2026 BMW G82 / G83 M4",
    fitments: [{ generationSlug: "g82-m4", yearStart: 2021, yearEnd: 2026, trims: ["M4", "M4 Competition", "M4 CSL"], exact: true, notes: "For M4 coupe and convertible. Minor trimming may be needed with aftermarket mud flaps." }],
    variants: [{ id: "var_g82_skirt_gloss", sku: "AH-G82-SKRT-CF-GLS", material: "Carbon Fiber", finish: "Gloss", optionLabel: "Gloss Carbon", price: 699, inventory: 0 }],
    shippingWindow: { processingBusinessDays: "5-8 Business Days", deliveryBusinessDays: "10-18 Business Days" },
    installation: "Professional installation recommended for best body-line alignment.",
    whatsIncluded: ["Driver side skirt", "Passenger side skirt", "Mounting kit"],
    faq: baseFaq,
    relatedSlugs: ["g80-csl-style-carbon-grille"],
  },
  {
    id: "prod_g20_mirror_caps",
    slug: "g20-m340i-carbon-mirror-caps",
    brandSlug: "bmw",
    brandName: "BMW",
    categorySlug: "mirror-caps",
    categoryName: "Mirror Caps",
    title: "BMW G20 M340i Carbon Mirror Caps",
    shortDescription: "OEM-replacement mirror caps with exposed carbon weave.",
    description: "A subtle finishing piece designed to match gloss carbon front and rear aero components.",
    price: 229,
    status: "Active",
    badges: ["BEST SELLER"],
    rating: 4.9,
    reviewCount: 57,
    featured: false,
    bestSeller: true,
    newArrival: false,
    materialOptions: ["Carbon Fiber"],
    finishOptions: ["Gloss", "Matte"],
    gallery: ["/assets/products/g20-m340i-carbon-mirror-caps-1.svg", "/assets/products/g20-m340i-carbon-mirror-caps-2.svg", "/assets/products/g20-m340i-carbon-mirror-caps-3.svg"],
    compatibilitySummary: "2019-2026 BMW G20 / G21 with standard mirror housing",
    fitments: [{ generationSlug: "g20", yearStart: 2019, yearEnd: 2026, trims: ["330i", "330e", "M340i"], exact: true, notes: "Compatible with standard G20/G21 mirror housings." }],
    variants: [
      { id: "var_g20_mirror_gloss", sku: "AH-G20-MCAP-CF-GLS", material: "Carbon Fiber", finish: "Gloss", optionLabel: "Gloss Carbon", price: 229, inventory: 16 },
      { id: "var_g20_mirror_matte", sku: "AH-G20-MCAP-CF-MAT", material: "Carbon Fiber", finish: "Matte", optionLabel: "Matte Carbon", price: 239, inventory: 10 },
    ],
    shippingWindow: { processingBusinessDays: "2-4 Business Days", deliveryBusinessDays: "7-14 Business Days" },
    installation: "Clip-on replacement. Install in a warm environment for easiest removal.",
    whatsIncluded: ["Driver cap", "Passenger cap"],
    faq: baseFaq,
    relatedSlugs: ["g20-m-performance-carbon-front-lip"],
  },
  {
    id: "prod_f80_tail_lights",
    slug: "f80-cs-style-oled-tail-lights",
    brandSlug: "bmw",
    brandName: "BMW",
    categorySlug: "tail-lights",
    categoryName: "Tail Lights",
    title: "BMW F80 CS Style OLED Tail Lights",
    shortDescription: "OLED-inspired rear lighting conversion for F80 and compatible F30 M Sport builds.",
    description: "A modernized rear signature with startup animation and smoked internal housing.",
    price: 799,
    compareAtPrice: 899,
    status: "Active",
    badges: ["SALE"],
    rating: 4.6,
    reviewCount: 21,
    featured: false,
    bestSeller: false,
    newArrival: false,
    materialOptions: ["Polycarbonate / LED"],
    finishOptions: ["Smoked"],
    gallery: ["/assets/products/f80-cs-style-oled-tail-lights-1.svg", "/assets/products/f80-cs-style-oled-tail-lights-2.svg", "/assets/products/f80-cs-style-oled-tail-lights-3.svg"],
    compatibilitySummary: "2015-2018 BMW F80 M3",
    fitments: [{ generationSlug: "f80-m3", yearStart: 2015, yearEnd: 2018, trims: ["M3", "M3 Competition", "M3 CS"], exact: true, notes: "Plug-and-play for F80. Coding may be recommended for optimal behavior." }],
    variants: [{ id: "var_f80_oled_smoked", sku: "AH-F80-TLGT-OLED-SMK", material: "Polycarbonate / LED", finish: "Smoked", optionLabel: "Smoked OLED", price: 799, compareAtPrice: 899, inventory: 6 }],
    shippingWindow: { processingBusinessDays: "3-6 Business Days", deliveryBusinessDays: "8-16 Business Days" },
    installation: "We recommend coding backup settings when retrofitting on modified vehicles.",
    whatsIncluded: ["Full four-piece tail light set", "Harness adapters"],
    faq: baseFaq,
    relatedSlugs: ["g20-m340i-carbon-mirror-caps"],
  },
  {
    id: "prod_w206_spoiler",
    slug: "w206-carbon-trunk-spoiler",
    brandSlug: "mercedes-benz",
    brandName: "Mercedes-Benz",
    categorySlug: "spoilers",
    categoryName: "Spoilers",
    title: "Mercedes W206 Carbon Trunk Spoiler",
    shortDescription: "Low-profile ducktail spoiler for W206 sedan trunk line.",
    description: "A restrained lip that adds tension to the W206 rear deck without overpowering the factory character line.",
    price: 269,
    status: "Active",
    badges: ["NEW"],
    rating: 4.7,
    reviewCount: 13,
    featured: true,
    bestSeller: false,
    newArrival: true,
    materialOptions: ["Carbon Fiber"],
    finishOptions: ["Gloss"],
    gallery: ["/assets/products/w206-carbon-trunk-spoiler-1.svg", "/assets/products/w206-carbon-trunk-spoiler-2.svg", "/assets/products/w206-carbon-trunk-spoiler-3.svg"],
    compatibilitySummary: "2022-2026 Mercedes-Benz W206 C-Class",
    fitments: [{ generationSlug: "w206", yearStart: 2022, yearEnd: 2026, trims: ["C300", "C43 AMG", "C63 S E Performance"], exact: true, notes: "Sedan only. Not for coupe applications." }],
    variants: [{ id: "var_w206_spoiler_gloss", sku: "AH-W206-SPLR-CF-GLS", material: "Carbon Fiber", finish: "Gloss", optionLabel: "Gloss Carbon", price: 269, inventory: 8 }],
    shippingWindow: { processingBusinessDays: "2-5 Business Days", deliveryBusinessDays: "7-15 Business Days" },
    installation: "Clean and prime the trunk surface before applying supplied tape.",
    whatsIncluded: ["Spoiler", "Adhesion promoter", "Pre-installed 3M tape"],
    faq: baseFaq,
    relatedSlugs: ["audi-b9-rs-style-front-lip"],
  },
  {
    id: "prod_b9_lip",
    slug: "audi-b9-rs-style-front-lip",
    brandSlug: "audi",
    brandName: "Audi",
    categorySlug: "front-lips",
    categoryName: "Front Lips",
    title: "Audi B9 RS Style Front Lip",
    shortDescription: "Sharper multi-piece lower splitter profile for B9 S-line and RS-inspired builds.",
    description: "Built to add visual width and a cleaner lower line for daily-driven street builds.",
    price: 379,
    status: "Active",
    badges: ["BEST SELLER"],
    rating: 4.8,
    reviewCount: 25,
    featured: true,
    bestSeller: true,
    newArrival: false,
    materialOptions: ["Carbon Fiber", "ABS"],
    finishOptions: ["Gloss", "Satin Black"],
    gallery: ["/assets/products/audi-b9-rs-style-front-lip-1.svg", "/assets/products/audi-b9-rs-style-front-lip-2.svg", "/assets/products/audi-b9-rs-style-front-lip-3.svg"],
    compatibilitySummary: "2017-2025 Audi B9 A4 / S4 / RS4",
    fitments: [{ generationSlug: "b9", yearStart: 2017, yearEnd: 2025, trims: ["A4", "S4", "RS4"], exact: false, notes: "Exact fit on S-line and S4 bumpers. Partial fitment on select A4 non-S-line with hardware adjustments.", exclusions: ["Not for Allroad"], requires: ["S-line or RS-style bumper preferred"] }],
    variants: [
      { id: "var_b9_lip_gloss", sku: "AH-B9-FLIP-CF-GLS", material: "Carbon Fiber", finish: "Gloss", optionLabel: "Gloss Carbon", price: 379, inventory: 12 },
      { id: "var_b9_lip_abs", sku: "AH-B9-FLIP-ABS-SBK", material: "ABS", finish: "Satin Black", optionLabel: "ABS / Satin Black", price: 289, inventory: 14 },
    ],
    shippingWindow: { processingBusinessDays: "2-5 Business Days", deliveryBusinessDays: "7-16 Business Days" },
    installation: "Partial-fitment trims should confirm bumper profile with AeroHaus fitment support before ordering.",
    whatsIncluded: ["Lip set", "Fastener kit"],
    faq: baseFaq,
    relatedSlugs: ["w206-carbon-trunk-spoiler"],
  },
  {
    id: "prod_982_ducktail",
    slug: "porsche-718-carbon-ducktail-spoiler",
    brandSlug: "porsche",
    brandName: "Porsche",
    categorySlug: "spoilers",
    categoryName: "Spoilers",
    title: "Porsche 718 Carbon Ducktail Spoiler",
    shortDescription: "Heritage-inspired ducktail for 982 Cayman and Boxster platforms.",
    description: "Adds a more purposeful rear profile while maintaining an OEM-plus silhouette suited to premium road builds.",
    price: 849,
    status: "Active",
    badges: ["NEW"],
    rating: 4.9,
    reviewCount: 11,
    featured: true,
    bestSeller: false,
    newArrival: true,
    materialOptions: ["Carbon Fiber"],
    finishOptions: ["Gloss"],
    gallery: ["/assets/products/porsche-718-carbon-ducktail-spoiler-1.svg", "/assets/products/porsche-718-carbon-ducktail-spoiler-2.svg", "/assets/products/porsche-718-carbon-ducktail-spoiler-3.svg"],
    compatibilitySummary: "2017-2025 Porsche 718 Cayman / Boxster 982",
    fitments: [{ generationSlug: "982", yearStart: 2017, yearEnd: 2025, trims: ["Cayman", "Cayman S", "GTS 4.0", "GT4"], exact: true, notes: "For 982 hatch profile. GT4 alignment differs slightly and should be verified prior to shipping." }],
    variants: [{ id: "var_982_ducktail_gloss", sku: "AH-982-DKTL-CF-GLS", material: "Carbon Fiber", finish: "Gloss", optionLabel: "Gloss Carbon", price: 849, inventory: 5 }],
    shippingWindow: { processingBusinessDays: "4-7 Business Days", deliveryBusinessDays: "10-18 Business Days" },
    installation: "Professional installation recommended due to decklid alignment sensitivity.",
    whatsIncluded: ["Ducktail spoiler", "Mounting hardware", "Seal strip"],
    faq: baseFaq,
    relatedSlugs: ["audi-b9-rs-style-front-lip"],
  },
  {
    id: "prod_g20_coilovers",
    slug: "bmw-g20-coilover-kit",
    brandSlug: "bmw",
    brandName: "BMW",
    categorySlug: "suspension",
    categoryName: "Suspension",
    title: "BMW G20 Street Performance Coilover Kit",
    shortDescription: "Daily-drivable height-adjustable suspension with matched damping curves.",
    description: "Built for enthusiasts who want a cleaner ride height and tighter body control without compromising regular use.",
    price: 1299,
    status: "Active",
    badges: ["BEST SELLER"],
    rating: 4.8,
    reviewCount: 17,
    featured: false,
    bestSeller: true,
    newArrival: false,
    materialOptions: ["Aluminum / Steel"],
    finishOptions: ["Anodized / Powder Coated"],
    gallery: ["/assets/products/bmw-g20-coilover-kit-1.svg", "/assets/products/bmw-g20-coilover-kit-2.svg", "/assets/products/bmw-g20-coilover-kit-3.svg"],
    compatibilitySummary: "2019-2026 BMW G20 330i / M340i",
    fitments: [{ generationSlug: "g20", yearStart: 2019, yearEnd: 2026, trims: ["330i", "M340i"], exact: true, notes: "Adaptive dampers require cancellation or compatible electronic module depending on trim." }],
    variants: [{ id: "var_g20_coilovers_std", sku: "AH-G20-COIL-STP", material: "Aluminum / Steel", finish: "Anodized / Powder Coated", optionLabel: "Street Performance", price: 1299, inventory: 6 }],
    shippingWindow: { processingBusinessDays: "3-6 Business Days", deliveryBusinessDays: "7-14 Business Days" },
    installation: "Four-wheel alignment required after installation.",
    whatsIncluded: ["Front coilovers", "Rear spring and damper kit", "Adjustment tools"],
    faq: baseFaq,
    relatedSlugs: ["g20-m-performance-carbon-front-lip"],
  },
  {
    id: "prod_g80_v_style_lip",
    slug: "bmw-g80-g82-v-style-dry-carbon-front-lip",
    brandSlug: "bmw",
    brandName: "BMW",
    categorySlug: "front-lips",
    categoryName: "Front Lips",
    title: "BMW G80 / G82 V Style Dry Carbon Front Lip",
    shortDescription: "Three-piece V-style dry carbon front lip for BMW G80 M3 and G82 M4.",
    description: "A more aggressive front-end option based on the supplier's public G8X V-style carbon listing, merchandised under AeroHaus with fitment-safe retail copy.",
    price: 629,
    compareAtPrice: 749,
    status: "Active",
    badges: ["NEW", "BEST SELLER"],
    rating: 4.9,
    reviewCount: 14,
    featured: true,
    bestSeller: true,
    newArrival: true,
    materialOptions: ["Dry Carbon Fiber"],
    finishOptions: ["Gloss UV Clear"],
    gallery: ["/assets/products/bmw-g80-g82-v-style-dry-carbon-front-lip-1.svg", "/assets/products/bmw-g80-g82-v-style-dry-carbon-front-lip-2.svg", "/assets/products/bmw-g80-g82-v-style-dry-carbon-front-lip-3.svg"],
    compatibilitySummary: "2021-2026 BMW G80 M3 / G82 M4",
    fitments: [
      { generationSlug: "g80-m3", yearStart: 2021, yearEnd: 2026, trims: ["M3", "M3 Competition", "M3 CS"], exact: true, notes: "V-style three-piece lip for G80 front bumper." },
      { generationSlug: "g82-m4", yearStart: 2021, yearEnd: 2026, trims: ["M4", "M4 Competition", "M4 CSL"], exact: true, notes: "Fits G82/G83 M4 bumper profile." }
    ],
    variants: [{ id: "var_g8x_v_style_gloss", sku: "AH-G8X-VLIP-DCF-GLS", material: "Dry Carbon Fiber", finish: "Gloss UV Clear", optionLabel: "Dry Carbon / Gloss", price: 629, compareAtPrice: 749, inventory: 7 }],
    shippingWindow: { processingBusinessDays: "3-6 Business Days", deliveryBusinessDays: "8-18 Business Days" },
    installation: "Dry-fit each section before fastening. Professional install recommended for optimal alignment.",
    whatsIncluded: ["Three-piece front lip", "Hardware kit", "Surface prep pads"],
    faq: baseFaq,
    relatedSlugs: ["g80-csl-style-carbon-grille", "g82-carbon-side-skirts"],
  },
  {
    id: "prod_w118_bodykit",
    slug: "mercedes-w118-cla45s-dry-carbon-bodykit",
    brandSlug: "mercedes-benz",
    brandName: "Mercedes-Benz",
    categorySlug: "body-kits",
    categoryName: "Body Kits",
    title: "Mercedes W118 / C118 AMG CLA45S Dry Carbon Body Kit",
    shortDescription: "Pre-preg dry carbon aero package for W118/C118 AMG CLA45S applications.",
    description: "Expanded from the supplier's public CLA45S bodykit listing, this package brings front splitter and aero trim merchandising into the AeroHaus Mercedes catalog.",
    price: 1499,
    compareAtPrice: 1699,
    status: "Preorder",
    badges: ["PREORDER", "NEW"],
    rating: 4.8,
    reviewCount: 6,
    featured: true,
    bestSeller: false,
    newArrival: true,
    materialOptions: ["Dry Carbon Fiber"],
    finishOptions: ["Gloss UV Clear"],
    gallery: ["/assets/products/mercedes-w118-cla45s-dry-carbon-bodykit-1.svg", "/assets/products/mercedes-w118-cla45s-dry-carbon-bodykit-2.svg", "/assets/products/mercedes-w118-cla45s-dry-carbon-bodykit-3.svg"],
    compatibilitySummary: "2020-2026 Mercedes-Benz CLA45 AMG W118 / C118",
    fitments: [{ generationSlug: "w118-cla", yearStart: 2020, yearEnd: 2026, trims: ["CLA45 AMG"], exact: true, notes: "Designed around W118 / C118 AMG CLA45S aero profile." }],
    variants: [{ id: "var_w118_bodykit_gloss", sku: "AH-W118-BKIT-DCF-GLS", material: "Dry Carbon Fiber", finish: "Gloss UV Clear", optionLabel: "Full Aero Kit", price: 1499, compareAtPrice: 1699, inventory: 0 }],
    shippingWindow: { processingBusinessDays: "5-9 Business Days", deliveryBusinessDays: "10-20 Business Days" },
    installation: "Professional installation strongly recommended. Body-kit alignment should be test-fit prior to drilling or permanent mounting.",
    whatsIncluded: ["Front splitter set", "Rear diffuser trim", "Side aero trim", "Hardware pack"],
    faq: baseFaq,
    relatedSlugs: ["w206-carbon-trunk-spoiler"],
  },
  {
    id: "prod_b85_aero_kit",
    slug: "audi-b85-carbon-aero-kit",
    brandSlug: "audi",
    brandName: "Audi",
    categorySlug: "body-kits",
    categoryName: "Body Kits",
    title: "Audi B8.5 Carbon Aero Kit",
    shortDescription: "Front lip, diffuser, spoiler and side skirt style package inspired by the supplier's public Audi multi-part listing.",
    description: "AeroHaus uses this as a bundled catalog entry for B8.5-era Audi customers who want a coordinated carbon exterior package rather than single-part shopping.",
    price: 1399,
    compareAtPrice: 1599,
    status: "Active",
    badges: ["NEW"],
    rating: 4.7,
    reviewCount: 10,
    featured: true,
    bestSeller: false,
    newArrival: true,
    materialOptions: ["Carbon Fiber"],
    finishOptions: ["Gloss UV Clear"],
    gallery: ["/assets/products/audi-b85-carbon-aero-kit-1.svg", "/assets/products/audi-b85-carbon-aero-kit-2.svg", "/assets/products/audi-b85-carbon-aero-kit-3.svg"],
    compatibilitySummary: "Audi B8.5 S4 / A4 S-line exterior package",
    fitments: [{ generationSlug: "b85", yearStart: 2013, yearEnd: 2016, trims: ["A4", "S4", "A5", "S5"], exact: false, notes: "Bundle listing spans B8.5 sport-package bumper profiles; confirm exact trim and body style before release.", exclusions: ["Not for Allroad"], requires: ["S-line or equivalent sport bumper"] }],
    variants: [{ id: "var_b85_aero_gloss", sku: "AH-B85-AERO-CFK-GLS", material: "Carbon Fiber", finish: "Gloss UV Clear", optionLabel: "4-Piece Aero Kit", price: 1399, compareAtPrice: 1599, inventory: 3 }],
    shippingWindow: { processingBusinessDays: "4-8 Business Days", deliveryBusinessDays: "9-18 Business Days" },
    installation: "Bundle is best installed together for panel-gap consistency and finish matching.",
    whatsIncluded: ["Front lip", "Rear diffuser", "Trunk spoiler", "Side skirt set"],
    faq: baseFaq,
    relatedSlugs: ["audi-b9-rs-style-front-lip"],
  },
  {
    id: "prod_992_front_lip",
    slug: "porsche-992-real-carbon-front-lip",
    brandSlug: "porsche",
    brandName: "Porsche",
    categorySlug: "front-lips",
    categoryName: "Front Lips",
    title: "Porsche 911 992 Real Carbon Front Bumper Lip",
    shortDescription: "Real carbon front lip for 992 Carrera-based front bumpers.",
    description: "AeroHaus retail adaptation of the supplier's publicly listed 992 real carbon front lip, rewritten for Porsche-focused storefront presentation.",
    price: 1099,
    compareAtPrice: 1249,
    status: "Active",
    badges: ["NEW"],
    rating: 4.9,
    reviewCount: 8,
    featured: true,
    bestSeller: false,
    newArrival: true,
    materialOptions: ["Real Carbon Fiber"],
    finishOptions: ["Gloss UV Clear"],
    gallery: ["/assets/products/porsche-992-real-carbon-front-lip-1.svg", "/assets/products/porsche-992-real-carbon-front-lip-2.svg", "/assets/products/porsche-992-real-carbon-front-lip-3.svg"],
    compatibilitySummary: "2020-2026 Porsche 911 992",
    fitments: [{ generationSlug: "992", yearStart: 2020, yearEnd: 2026, trims: ["Carrera", "Carrera S", "Turbo", "GT3"], exact: false, notes: "Source listing covers 992 front bumper applications. AeroHaus fitment support should verify trim-specific lower bumper geometry prior to release." }],
    variants: [{ id: "var_992_front_lip_gloss", sku: "AH-992-FLIP-RCF-GLS", material: "Real Carbon Fiber", finish: "Gloss UV Clear", optionLabel: "Real Carbon / Gloss", price: 1099, compareAtPrice: 1249, inventory: 4 }],
    shippingWindow: { processingBusinessDays: "4-7 Business Days", deliveryBusinessDays: "10-18 Business Days" },
    installation: "Professional install recommended due to low ride-height clearance and precision alignment.",
    whatsIncluded: ["Front lip assembly", "Hardware kit"],
    faq: baseFaq,
    relatedSlugs: ["porsche-718-carbon-ducktail-spoiler"],
  },

  {
    id: "prod_982_rear_diffuser",
    slug: "porsche-718-carbon-rear-diffuser",
    brandSlug: "porsche",
    brandName: "Porsche",
    categorySlug: "rear-diffusers",
    categoryName: "Rear Diffusers",
    title: "Porsche 718 Carbon Rear Bumper Diffuser",
    shortDescription: "Real carbon rear diffuser for Porsche 718 Cayman and Boxster rear bumper applications.",
    description: "Added from the supplier's public Porsche collection, this diffuser expands the 718 section with a rear-end aero option instead of only spoilers.",
    price: 949,
    compareAtPrice: 1099,
    status: "Active",
    badges: ["NEW"],
    rating: 4.8,
    reviewCount: 5,
    featured: true,
    bestSeller: false,
    newArrival: true,
    materialOptions: ["Real Carbon Fiber"],
    finishOptions: ["Gloss UV Clear"],
    gallery: ["/assets/products/porsche-718-carbon-rear-diffuser-1.svg", "/assets/products/porsche-718-carbon-rear-diffuser-2.svg", "/assets/products/porsche-718-carbon-rear-diffuser-3.svg"],
    compatibilitySummary: "2017-2018 Porsche 718 Boxster / Cayman",
    fitments: [{ generationSlug: "982", yearStart: 2017, yearEnd: 2018, trims: ["Cayman", "Cayman S", "GTS 4.0", "GT4"], exact: false, notes: "Supplier listing specifically references early 718 rear bumper applications. Confirm exact model year and lower valance before release." }],
    variants: [{ id: "var_982_diffuser_gloss", sku: "AH-982-RDIF-RCF-GLS", material: "Real Carbon Fiber", finish: "Gloss UV Clear", optionLabel: "Real Carbon / Gloss", price: 949, compareAtPrice: 1099, inventory: 4 }],
    shippingWindow: { processingBusinessDays: "4-7 Business Days", deliveryBusinessDays: "10-18 Business Days" },
    installation: "Professional installation recommended for diffuser trim alignment and exhaust clearance checks.",
    whatsIncluded: ["Rear diffuser", "Hardware pack"],
    faq: baseFaq,
    relatedSlugs: ["porsche-718-carbon-ducktail-spoiler", "porsche-992-real-carbon-front-lip"],
  },
  {
    id: "prod_9922_rear_diffuser",
    slug: "porsche-9922-dry-carbon-rear-diffuser",
    brandSlug: "porsche",
    brandName: "Porsche",
    categorySlug: "rear-diffusers",
    categoryName: "Rear Diffusers",
    title: "Porsche 911 992.2 Dry Carbon Rear Diffuser",
    shortDescription: "Dry carbon rear diffuser for Porsche 911 Carrera 992.2 2024-on applications.",
    description: "AeroHaus adaptation of the supplier's public 992.2 diffuser listing, positioned as a premium rear styling piece for the facelifted 911 platform.",
    price: 1289,
    compareAtPrice: 1429,
    status: "Preorder",
    badges: ["PREORDER", "NEW"],
    rating: 4.9,
    reviewCount: 3,
    featured: true,
    bestSeller: false,
    newArrival: true,
    materialOptions: ["Dry Carbon Fiber"],
    finishOptions: ["Gloss UV Clear"],
    gallery: ["/assets/products/porsche-9922-dry-carbon-rear-diffuser-1.svg", "/assets/products/porsche-9922-dry-carbon-rear-diffuser-2.svg", "/assets/products/porsche-9922-dry-carbon-rear-diffuser-3.svg"],
    compatibilitySummary: "2024-2026 Porsche 911 Carrera 992.2",
    fitments: [{ generationSlug: "992", yearStart: 2024, yearEnd: 2026, trims: ["Carrera", "Carrera S", "Turbo", "GT3"], exact: false, notes: "Supplier listing references 992.2 Carrera rear-end geometry. AeroHaus fitment support should verify trim-specific exhaust and bumper layout." }],
    variants: [{ id: "var_9922_diffuser_gloss", sku: "AH-9922-RDIF-DCF-GLS", material: "Dry Carbon Fiber", finish: "Gloss UV Clear", optionLabel: "Dry Carbon / Gloss", price: 1289, compareAtPrice: 1429, inventory: 0 }],
    shippingWindow: { processingBusinessDays: "5-8 Business Days", deliveryBusinessDays: "10-20 Business Days" },
    installation: "Best installed by a specialist familiar with Porsche rear bumper trim and sensor alignment.",
    whatsIncluded: ["Rear diffuser", "Mounting kit"],
    faq: baseFaq,
    relatedSlugs: ["porsche-992-real-carbon-front-lip"],
  },
  {
    id: "prod_9y_spoiler",
    slug: "porsche-cayenne-9y-carbon-rear-spoiler",
    brandSlug: "porsche",
    brandName: "Porsche",
    categorySlug: "spoilers",
    categoryName: "Spoilers",
    title: "Porsche Cayenne 9Y Carbon Rear Spoiler",
    shortDescription: "Carbon-look rear roof spoiler for Cayenne 9YA / 9YB applications.",
    description: "Built from the supplier's public Cayenne 9Y collection items, this gives AeroHaus a Porsche SUV entry point with strong daily-driver styling appeal.",
    price: 519,
    compareAtPrice: 629,
    status: "Active",
    badges: ["NEW"],
    rating: 4.7,
    reviewCount: 4,
    featured: true,
    bestSeller: false,
    newArrival: true,
    materialOptions: ["ABS Carbon Fiber Look"],
    finishOptions: ["Gloss"],
    gallery: ["/assets/products/porsche-cayenne-9y-carbon-rear-spoiler-1.svg", "/assets/products/porsche-cayenne-9y-carbon-rear-spoiler-2.svg", "/assets/products/porsche-cayenne-9y-carbon-rear-spoiler-3.svg"],
    compatibilitySummary: "2019-2026 Porsche Cayenne 9YA / 9YB",
    fitments: [{ generationSlug: "9y-cayenne", yearStart: 2019, yearEnd: 2026, trims: ["Cayenne", "Cayenne S", "Cayenne Coupe", "Cayenne GT"], exact: false, notes: "Confirm SUV vs Coupe roofline before release. Supplier catalog covers both 9YA and 9YB references." }],
    variants: [{ id: "var_9y_spoiler_gloss", sku: "AH-9Y-SPLR-ABS-GLS", material: "ABS Carbon Fiber Look", finish: "Gloss", optionLabel: "Gloss Carbon Look", price: 519, compareAtPrice: 629, inventory: 6 }],
    shippingWindow: { processingBusinessDays: "3-6 Business Days", deliveryBusinessDays: "9-18 Business Days" },
    installation: "Surface prep and alignment are critical due to the Cayenne roof spoiler profile.",
    whatsIncluded: ["Rear spoiler", "Pre-applied tape", "Adhesion promoter"],
    faq: baseFaq,
    relatedSlugs: ["porsche-992-real-carbon-front-lip"],
  },
  {
    id: "prod_95b_widebody",
    slug: "porsche-macan-hm-style-wide-body-kit",
    brandSlug: "porsche",
    brandName: "Porsche",
    categorySlug: "body-kits",
    categoryName: "Body Kits",
    title: "Porsche Macan HM Style Wide Body Kit",
    shortDescription: "Front spoiler, rear diffuser and flare-style body kit package for Porsche Macan facelift builds.",
    description: "Mapped from the supplier's public Macan HM-style body kit listing, this adds a broader SUV styling package to AeroHaus Porsche offerings.",
    price: 2299,
    compareAtPrice: 2599,
    status: "Preorder",
    badges: ["PREORDER", "NEW"],
    rating: 4.6,
    reviewCount: 2,
    featured: true,
    bestSeller: false,
    newArrival: true,
    materialOptions: ["Composite / Carbon Fiber Mix"],
    finishOptions: ["Unpainted", "Gloss Carbon Accents"],
    gallery: ["/assets/products/porsche-macan-hm-style-wide-body-kit-1.svg", "/assets/products/porsche-macan-hm-style-wide-body-kit-2.svg", "/assets/products/porsche-macan-hm-style-wide-body-kit-3.svg"],
    compatibilitySummary: "2015-2021 Porsche Macan 95B",
    fitments: [{ generationSlug: "95b-macan", yearStart: 2015, yearEnd: 2021, trims: ["Macan", "Macan S", "Macan GTS", "Macan Turbo"], exact: false, notes: "Supplier listing references facelift and wide-flare body kit fitment. AeroHaus fitment support should confirm bumper generation before release." }],
    variants: [{ id: "var_95b_bodykit_unpainted", sku: "AH-95B-BKIT-CMP-UP", material: "Composite / Carbon Fiber Mix", finish: "Unpainted", optionLabel: "Unpainted Kit", price: 2299, compareAtPrice: 2599, inventory: 0 }],
    shippingWindow: { processingBusinessDays: "6-10 Business Days", deliveryBusinessDays: "12-24 Business Days" },
    installation: "Professional body shop installation required for flare alignment and finishing.",
    whatsIncluded: ["Front spoiler", "Rear diffuser", "Wide flare set", "Hardware kit"],
    faq: baseFaq,
    relatedSlugs: ["porsche-cayenne-9y-carbon-rear-spoiler"],
  },
];

export const featuredReviews: ProductReview[] = [
  { id: "rev_1", customer: "Demo Customer A", rating: 5, title: "Fitment team caught a bumper difference before shipment", review: "Placeholder development review data. Great communication, clean packaging, and the carbon weave matched the rest of the build well.", vehicle: "2024 BMW M340i G20", verifiedPurchase: true, photos: ["/assets/social-feed.svg"], date: "2026-08-01", approved: true },
  { id: "rev_2", customer: "Demo Customer B", rating: 5, title: "Premium presentation and easy install", review: "Placeholder development review data. The part arrived within the quoted window and looked right at home on the car.", vehicle: "2022 Mercedes-Benz C300 W206", verifiedPurchase: true, photos: [], date: "2026-07-26", approved: true },
  { id: "rev_3", customer: "Demo Customer C", rating: 4, title: "Exactly the look I wanted", review: "Placeholder development review data. Support helped clarify the trim compatibility before checkout.", vehicle: "2023 Porsche 718 Cayman 982", verifiedPurchase: false, photos: [], date: "2026-07-18", approved: true },
];

export const builds: Build[] = [
  { id: "build_g80", slug: "the-aerohaus-g80", title: "THE AEROHAUS G80", subtitle: "A sharper daily-driven M3 with purposeful carbon details.", vehicleLabel: "2024 BMW G80 M3 Competition", description: "An editorial-style demo build designed to show how AeroHaus can merchandise complete styling packages rather than isolated SKUs.", heroImage: "/assets/build-g80.svg", gallery: ["/assets/build-g80.svg", "/assets/build-g80-alt.svg", "/assets/build-g80-detail.svg"], productSlugs: ["g80-csl-style-carbon-grille", "g82-carbon-side-skirts", "g20-m-performance-carbon-front-lip"] },
  { id: "build_g20", slug: "m340i-street-series", title: "M340I STREET SERIES", subtitle: "OEM-plus aero with coilovers and mirror details.", vehicleLabel: "2024 BMW M340i G20 LCI", description: "A street-focused package centered around the G20 front lip, mirror caps and chassis drop.", heroImage: "/assets/build-g20.svg", gallery: ["/assets/build-g20.svg", "/assets/build-g20-alt.svg"], productSlugs: ["g20-m-performance-carbon-front-lip", "g20-m340i-carbon-mirror-caps", "bmw-g20-coilover-kit"] },
];

export const demoOrders: DemoOrder[] = [
  {
    orderNumber: "AH-100241",
    email: "demo@aerohaus.dev",
    status: "In Transit",
    items: [
      { productSlug: "g20-m-performance-carbon-front-lip", variantId: "var_g20_front_lip_gloss", quantity: 1 },
      { productSlug: "g20-m340i-carbon-mirror-caps", variantId: "var_g20_mirror_gloss", quantity: 1 },
    ],
    trackingNumber: "AHX784920184US",
    carrier: "DHL eCommerce",
    timeline: [
      { status: "pending", label: "Order Confirmed", date: "Aug 2, 2026", complete: true },
      { status: "processing", label: "Processing", date: "Aug 4, 2026", complete: true },
      { status: "supplier", label: "Supplier Processing", date: "Aug 6, 2026", complete: true },
      { status: "shipped", label: "Shipped", date: "Aug 8, 2026", complete: true },
      { status: "transit", label: "In Transit", date: "Aug 10, 2026", complete: true },
      { status: "delivery", label: "Out for Delivery", date: "Pending", complete: false },
      { status: "delivered", label: "Delivered", date: "Pending", complete: false },
    ],
  },
];
